app/core/urls.py
from django.urls import path
from app.core import views
from django.conf import settings
from django.conf.urls.static import static
from app.core.view.paciente_views import PacienteListView, PacienteCreateView, PacienteUpdateView, PacienteDeleteView
from app.core.view.escaneo_views import AnalisisImagenView , BuscarPacienteAPIView,ProcesarAnalisisAPIView, DiagnosticoDeleteView
from app.core.view.report_views import ReportListView,ReportDetailView
from app.core.view.revision_escaneo import RevisionManualView, ValidarResultadoView
from app.core.views import statistics_view
from app.core.view.settings_views import (
    SettingsView, UpdateProfileView, UpdateProfileImageView,
    UpdatePasswordView, UpdateNotificationsView,
    UpdateAppearanceView, UpdateSystemSettingsView,
    GoogleAuthView, UnlinkGoogleAccountView, GoogleAuthCallbackView
)
from app.core.view.doctor_views import DoctorCreateView, DoctorListView

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('pacientes/', PacienteListView.as_view(), name='pacient_list'),
    path('pacientes/crear/', PacienteCreateView.as_view(), name='pacient_create'),
    path('pacientes/editar/<int:pk>/', PacienteUpdateView.as_view(), name='pacient_update'),
    path('pacientes/eliminar/<int:pk>/', PacienteDeleteView.as_view(), name='pacient_delete'),
    path('scan_list/', views.scan_list, name='scan_list'),
    path('scan/eliminar/<int:pk>/', DiagnosticoDeleteView.as_view(), name='scan_delete'),
    path('procesar-analisis/', AnalisisImagenView.as_view(), name='form_procesar_analisis'),
    path('api/buscar-paciente/', BuscarPacienteAPIView.as_view(), name='buscar_paciente_dni'),
    path('api/procesar-analisis/', ProcesarAnalisisAPIView.as_view(), name='procesar_analisis'),
    path('report_list/', ReportListView.as_view(), name='report_list'),
    path('report_detail/<int:pk>/', ReportDetailView.as_view(), name='report_detail'),
    
    # URLs de revisión manual
    path('revision-manual/', RevisionManualView.as_view(), name='revision_manual'),
    path('revision-manual/<int:diagnostico_id>/', RevisionManualView.as_view(), name='revision_manual_detalle'),
    path('validar-resultado/<int:diagnostico_id>/', ValidarResultadoView.as_view(), name='validar_resultado'),
    
    # URLs de configuración
    path('settings/', SettingsView.as_view(), name='settings'),
    path('settings/profile/update/', UpdateProfileView.as_view(), name='update_profile'),
    path('statistics/', statistics_view, name='statistics'),
    path('settings/profile/image/', UpdateProfileImageView.as_view(), name='update_profile_image'),
    path('settings/password/', UpdatePasswordView.as_view(), name='update_password'),
    path('settings/notifications/', UpdateNotificationsView.as_view(), name='update_notifications'),
    path('settings/appearance/', UpdateAppearanceView.as_view(), name='update_appearance'),
    path('settings/system/', UpdateSystemSettingsView.as_view(), name='update_system_settings'),
    path('settings/google/auth/', GoogleAuthView.as_view(), name='google_auth'),
    path('settings/google/unlink/', UnlinkGoogleAccountView.as_view(), name='unlink_google'),
    path('settings/google/callback/', GoogleAuthCallbackView.as_view(), name='google_callback'),
    path('doctor/create/', DoctorCreateView.as_view(), name='doctor_create'),
    path('doctores/', DoctorListView.as_view(), name='doctor_list'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/security/urls.py
from django.urls import path
from app.security import views
from app.security.views import GoogleLoginView, GoogleLoginCallbackView

app_name = 'security'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('google/login/', GoogleLoginView.as_view(), name='google_login'),
    path('google/callback/', GoogleLoginCallbackView.as_view(), name='google_login_callback'),
]

neumscan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.core.urls')),
    path('security/', include('app.security.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NeumScan - Sistema de Gestión de Escaneos</title>
    
 
    <!-- ======= Styles ====== -->
    <link rel="stylesheet" href="{% static 'css/styless.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    
    {% block extra_css %}{% endblock %}
</head>

<body>
    <!-- Loader -->
    <div class="loader-wrapper">
        <div class="loader"></div>
    </div>

    <!-- Contenido principal -->
    <div class="container">
        <div class="navigation">
            <ul>
                <li>
                    <a href="{% url 'core:home' %}">
                        <span class="icon">
                            <ion-icon name="pulse-outline"></ion-icon>
                        </span>
                        <span class="title">NEUMSCAN</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'core:dashboard' %}">
                        <span class="icon">
                            <ion-icon name="home-outline"></ion-icon>
                        </span>
                        <span class="title">Dashboard</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'core:pacient_list' %}">
                        <span class="icon">
                            <ion-icon name="people-outline"></ion-icon>
                        </span>
                        <span class="title">Pacientes</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'core:scan_list' %}">
                        <span class="icon">
                            <ion-icon name="scan-outline"></ion-icon>
                        </span>
                        <span class="title">Escaneos</span>
                    </a>
                </li>

                

                <li>
                    <a href="{% url 'core:report_list' %}">
                        <span class="icon">
                            <ion-icon name="document-text-outline"></ion-icon>
                        </span>
                        <span class="title">Reportes</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'core:statistics' %}">
                        <span class="icon">
                            <ion-icon name="stats-chart-outline"></ion-icon>
                        </span>
                        <span class="title">Estadísticas</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'core:settings' %}">
                        <span class="icon">
                            <ion-icon name="settings-outline"></ion-icon>
                        </span>
                        <span class="title">Configuración</span>
                    </a>
                </li>
                <li>
                    {% if user.is_superuser %}
                    <a href="{% url 'core:doctor_list' %}">
                        <span class="icon">
                            <ion-icon name="person-add-outline"></ion-icon>
                        </span>
                        <span class="title">Crear Cuenta Doctor</span>
                    </a>
                    {% endif %}
                </li>

                <li>
                    <a href="{% url 'security:logout' %}">
                        <span class="icon">
                            <ion-icon name="log-out-outline"></ion-icon>
                        </span>
                        <span class="title">Cerrar Sesión</span>
                    </a>
                </li>
            </ul>
        </div>

        <!-- ========================= Main ==================== -->
        <div class="main">
            <div class="topbar">
                <div class="toggle">
                    <ion-icon name="menu-outline"></ion-icon>
                </div>
            </div>

            <!-- Mensajes de alerta -->
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endfor %}
            </div>
            {% endif %}

            {%block content%}
            {%endblock%}
        </div>
    </div>

    <!-- Scripts -->
    <!-- jQuery first, then Bootstrap Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    
    <!-- Custom Scripts -->
    <script src="{% static 'js/main.js' %}"></script>

    <!-- ====== ionicons ======= -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

    {% block extra_js %}{% endblock %}

    <script>
        // Función mejorada para manejar el loader
        document.addEventListener("DOMContentLoaded", function () {
            setTimeout(() => {
                const loader = document.querySelector(".loader-wrapper");
                if (loader) {
                    loader.style.opacity = "0";
                    setTimeout(() => {
                        loader.style.display = "none";
                    }, 500);
                }
            }, 1000);
        });

        // Función para el toggle de navegación
        function toggleNavigation() {
            const navigation = document.querySelector('.navigation');
            const main = document.querySelector('.main');

            if (navigation && main) {
                navigation.classList.toggle('collapsed');
                main.classList.toggle('expanded');
            }
        }

        // Agregar funcionalidad al botón de toggle
        document.addEventListener('DOMContentLoaded', function () {
            const toggleBtn = document.querySelector('.toggle');
            if (toggleBtn) {
                toggleBtn.addEventListener('click', toggleNavigation);
            }
        });

        // Oculta automáticamente los mensajes después de 3 segundos
        setTimeout(function() {
            document.querySelectorAll('.messages .alert').forEach(function(alert) {
                alert.style.transition = "opacity 0.5s";
                alert.style.opacity = "0";
                setTimeout(function() {
                    alert.style.display = "none";
                }, 500);
            });
        }, 3000);
    </script>
</body>

</html>